export default {
  common: {
    newVisits: 'New Visits',
    messages: 'Messages',
    purchases: 'Purchases',
    shoppings: 'Shoppings',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    sun: 'Sun',
    edit: 'Edit',
    actions: 'Actions',
    delivery: 'Delivery',
    contactCustomer: 'Contact Customer',
    urgent: 'Urgent',
    reply: 'Reply',
    globalSize: 'Global Size',
  },
  states: {
    pending: 'Pending',
    normal: 'Normal',
    suspended: 'Suspended',
    pause: 'Paused',
    delivery: 'Delivery',
    received: 'Received',
    rejected: 'Rejected',
    minutesBefore: 'minutes before',
  },
  chart: {
    expected: 'Expected',
    actual: 'Actual',
    raddar: {
      sales: 'Sales',
      administration: 'Administration',
      information_technology: 'Information Technology',
      customer_support: 'Customer Support',
      development: 'Development',
      marketing: 'Marketing',
      allocated_budget: 'Allocated Budget',
      expected_spending: 'Expected Spending',
      actual_spending: 'Actual Spending',
    },
    pie: {
      title: 'Capital Reserve',
      cash: 'Cash',
      draft: 'Draft',
      forex: 'Forex',
      gold: 'Gold',
      stock: 'Stock',
    },
    transaction: {
      orderNo: 'Order No',
      price: 'Price',
      status: 'Status',
    },
    todoList: {
      title: 'Todo List',
      itemsLeft: 'items left',
    },
  },
  nav: {
    dashboard: 'Dashboard',
    permission: 'Permission',
    pagePermission: 'Page Permission',
    rolePermission: 'Role Permission',
    product: 'Product Management',
    order: 'Order Management',
    customer: 'Customer Management',
    message: 'Messages',
    logout: 'Log Out',
  },
  product: {
    columns: {
      name: 'Name',
      price: 'Price',
      states: 'States',
      inStock: 'In Stock',
      heat: 'Heat',
      expires: 'Expires',
    },
  },
  order: {
    columns: {
      name: 'Name',
      orderNo: 'Order No',
      zip: 'Zip Code',
      orderTime: 'Order Time',
      states: 'States',
    },
  },
  customer: {
    columns: {
      name: 'Name',
      sales: 'Sales',
      phone: 'Phone',
      email: 'E-mail',
      vip: 'Is VIP',
    },
  },
  message: {
    columns: {
      ticketNo: 'Ticket No',
      customer: 'Customer',
      type: 'Type',
      title: 'Title',
    },
    types: {
      bug: 'Bug',
      advise: 'Advise',
      support: 'Support',
    },
  },
  role: {
    yourRole: 'Your roles:',
    switchRole: 'Switch roles:',
    roles: {
      admin: 'Admin',
      editor: 'Editor',
    },
  },
  login: {
    title: 'Login',
    loginBtn: 'Login',
    tipUsername: 'Username:',
    tipPassword: 'Password:',
  },
};