export default {
  common: {
    newVisits: '新访问',
    messages: '消息',
    purchases: '付款',
    shoppings: '商品',
    mon: '周一',
    tue: '周二',
    wed: '周三',
    thu: '周四',
    fri: '周五',
    sat: '周六',
    sun: '周日',
    edit: '编辑',
    actions: '操作',
    minutesBefore: '分钟前',
    delivery: '配送',
    contactCustomer: '联系客户',
    urgent: '紧急',
    reply: '回复',
    globalSize: '全局大小',
  },
  states: {
    pending: '等待',
    normal: '正常',
    suspended: '已下线',
    pause: '暂停',
    delivery: '配送中',
    received: '已签收',
    rejected: '拒收',
  },
  chart: {
    expected: '预期',
    actual: '实际',
    raddar: {
      sales: '销售',
      administration: '管理',
      information_technology: '信息技术',
      customer_support: '客服',
      development: '开发',
      marketing: '市场',
      allocated_budget: '分配预算',
      expected_spending: '预期支出',
      actual_spending: '实际支出',
    },
    pie: {
      title: '资金储备',
      cash: '现金',
      draft: '汇票',
      forex: '外汇',
      gold: '黄金',
      stock: '股票',
    },
    transaction: {
      orderNo: '订单号',
      price: '价格',
      status: '状态',
    },
    todoList: {
      title: '待办列表',
      itemsLeft: '项剩余',
    },
  },
  nav: {
    dashboard: '首页',
    permission: '权限',
    pagePermission: '页面权限',
    rolePermission: '角色权限',
    product: '商品管理',
    order: '订单管理',
    customer: '客户管理',
    message: '消息',
    logout: '退出登录',
  },
  product: {
    columns: {
      name: '名称',
      price: '价格',
      states: '状态',
      inStock: '库存',
      heat: '热度',
      expires: '有效期',
    },
  },
  order: {
    columns: {
      name: '姓名',
      orderNo: '订单号',
      zip: '邮编',
      orderTime: '订单时间',
      states: '订单状态',
    },
  },
  customer: {
    columns: {
      name: '姓名',
      sales: '销售量',
      phone: '电话',
      email: 'E-mail',
      vip: '重点客户',
    },
  },
  message: {
    columns: {
      ticketNo: '工单号',
      customer: '客户',
      type: '类别',
      title: '标题',
    },
    types: {
      bug: '系统Bug',
      advise: '建议',
      support: '技术支持',
    },
  },
  role: {
    yourRole: '你的角色：',
    switchRole: '切换角色：',
    roles: {
      admin: '管理员',
      editor: '编辑员',
    },
  },
  login: {
    title: '登录',
    loginBtn: '登录',
    tipUsername: '用户名：',
    tipPassword: '密码：',
  },
};